name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.4.0
  crypto: ^3.0.5
  dotenv: ^4.2.0
  get_it: ^7.7.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  mime: ^1.0.5
  mongo_dart: ^0.10.3
  shared: 
    path: ../shared
  shelf: ^1.4.0
  shelf_multipart: ^2.0.0
  shelf_router: ^1.1.0
  uuid: ^4.4.2

dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
